version: '3.8'

services:
  web:
    build: .
    container_name: linkmanager_web
    ports:
      - "80:5000"
    volumes:
      - .:/app  # Para desarrollo, monta todo el código
      - db_data:/app/database  # Volumen dedicado para la carpeta donde estará database.db
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

volumes:
  db_data:
